---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo
spec:
  commonName: echo
  secretName: echo-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
