---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trust-manager-usage-server
resources:
  - certificate.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
replacements:
  - source:
      kind: Service
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.*
        options:
          delimiter: '.'
          index: 1
