---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: my-selfsigned-ca
spec:
  sources:
    - secret:
        name: root-secret
        key: ca.crt
  target:
    configMap:
      key: trust-bundle.pem
    additionalFormats:
      jks:
        key: trust-bundle.jks