---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo
spec:
  commonName: echo.SERVICE_NAMESPACE.svc.cluster.local
  dnsNames:
    - echo.SERVICE_NAMESPACE.svc
    - echo.SERVICE_NAMESPACE.svc.cluster.local
  secretName: echo-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
