---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      containers:
        - name: app
          image: ghcr.io/mendhak/http-https-echo:29
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: tls-cert
              mountPath: /app/fullchain.pem
              subPath: tls.crt
            - name: tls-cert
              mountPath: /app/privkey.pem
              subPath: tls.key
      volumes:
        - name: tls-cert
          secret:
            secretName: echo-tls
