---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trust-manager-usage
configMapGenerator:
  - name: ssl-poke-src
    files:
      - SSLPoke.java
generatorOptions:
  disableNameSuffixHash: true